### ISSUE TITLE
types and required

### ISSUE THREAD

**Issue by pgherveou** [pkaminski/fireplan#3]
Hey thks for your lib, you saved me so much typing!
I just noticed that you couldn't mark a referenced type as being required
I had a quick look at your code but couldn't find where to make the update :(

```
root:
  foo: &fooType
    bar: string
    baz: required number
  qux: required *fooType
```

**Comment by pkaminski** [comment]
Cool, glad you found it useful!  The reference types are built-in feature of YAML so customizing how they work would be hard, but try this:

```
root:
  foo: &fooType
    bar: string
    baz: required number
  qux:
    .value: required
    <<: *fooType
```

I'm not sure it'll work, though -- let me know!  Also, if `foo` happens to have a `.value` child, it'll be overwritten in the `qux` reference.
