### ISSUE TITLE
Issue with RuleDataSnapshot field as argument

### ISSUE THREAD

**Issue by dreadjr** [pkaminski/fireplan#5]
Maybe i am misunderstanding how this is supposed to work in fireplan, but here are my rules.yaml and the output, you can see the `newData.foo` is written directly not `newData.child('foo').val()`

``` yaml
functions:
  - testInner(foo, bar): root.data[foo][bar].exists()
  - test(): testInner(next.foo, next.bar)
  - testSingle(): root.data[next.foo][next.bar].exists()

root:
  test:
    .write: test()
  testSingle:
    .write: testSingle()
  testInner:
    .write: testInner(next.foo, next.bar)
```

``` json
{
  "rules": {
    "test": {
      ".write": "root.child('data').child(newData.foo).child(newData.bar).exists()",
      "$other": {
        ".validate": false
      }
    },
    "testSingle": {
      ".write": "root.child('data').child(newData.child('foo').val()).child(newData.child('bar').val()).exists()",
      "$other": {
        ".validate": false
      }
    },
    "testInner": {
      ".write": "root.child('data').child(newData.foo).child(newData.bar).exists()",
      "$other": {
        ".validate": false
      }
    },
    "$other": {
      ".validate": false
    }
  }
}
```

Simple ruleset

``` yaml
functions:
  - test(foo): root[foo].exists()
  - test2(next): root[next.foo].exists()

root:
  test:
    .write: test(next.foo)
  test2:
    .write: test2(next)
```
